#!/bin/bash

#SBATCH --partition=lotus_gpu

#SBATCH --account=lotus_gpu

#SBATCH --gres=gpu:2 # Request a number of GPUs

#SBATCH --time=20:00:00 # Set a runtime for the job in HH:MM:SS

#SBATCH --mem=64000 # Set the amount of memory for the job in MB.

conda activate venv-baseline

srun /gws/nopw/j04/ai4er/users/jl2182/gtc-exposure/change_detection/xBD/xView2_baseline/model/inference.sh  -x  /gws/nopw/j04/ai4er/users/jl2182/gtc-exposure/change_detection/xBD/xView2_baseline  -i /gws/nopw/j04/ai4er/users/jl2182/gtc-exposure/change_detection/xBD/xView2_baseline/inference/test_data/hurricane-matthew_00000010_post_disaster.png  -p /gws/nopw/j04/ai4er/users/jl2182/gtc-exposure/change_detection/xBD/xView2_baseline/inference/test_data/hurricane-matthew_00000010_post_disaster.png  -l /gws/nopw/j04/ai4er/users/jl2182/gtc-exposure/change_detection/xBD/xView2_baseline/inference/localisation_weights/model_iter_9951  -c /gws/nopw/j04/ai4er/users/jl2182/gtc-exposure/change_detection/xBD/xView2_baseline/inference/damage_weights/classification_weights-saved-model-89-0.39.hdf5  -o /gws/nopw/j04/ai4er/users/jl2182/gtc-exposure/change_detection/xBD/xView2_baseline/inference/test_output   -y
