#!/bin/bash

#SBATCH --partition=lotus_gpu

#SBATCH --account=lotus_gpu

#SBATCH --gres=gpu:3 # Request a number of GPUs

#SBATCH --time=12:00:00 # Set a runtime for the job in HH:MM:SS

#SBATCH --mem=64000 # Set the amount of memory for the job in MB.

conda activate venv-baseline

srun python train_model.py /gws/nopw/j04/ai4er/users/jl2182/xbd/disaster_data/spacenet_gt/dataSet/ /gws/nopw/j04/ai4er/users/jl2182/xbd/disaster_data/spacenet_gt/images/ /gws/nopw/j04/ai4er/users/jl2182/xbd/disaster_data/spacenet_gt/labels -o /gws/nopw/j04/ai4er/users/jl2182/gtc-exposure/change_detection/xBD/xView2_baseline/spacenet/src/models/model1_output/ -e 100
