name: exposure
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - pandas
  - numpy
  - matplotlib
  - scipy
  - jupyter
  - pillow
  - pytorch=1.7
  - pip
  - pip:
    - pytorch-lightning
    - wandb
    - numba<0.52
    - xlrd # these last two let you write excel files with datetimes in them.
    - openpyxl
