#!/bin/bash

#SBATCH --partition=lotus_gpu

#SBATCH --account=lotus_gpu

#SBATCH --gres=gpu:2 # Request a number of GPUs

#SBATCH --time=20:00:00 # Set a runtime for the job in HH:MM:SS

#SBATCH --mem=64000 # Set the amount of memory for the job in MB.

conda activate venv-baseline

srun python damage_classification.py --train_data /gws/nopw/j04/ai4er/users/jl2182/xbd/small_damage_classification/output --train_csv /gws/nopw/j04/ai4er/users/jl2182/xbd/small_damage_classification/output_csv/train.csv --test_data /gws/nopw/j04/ai4er/users/jl2182/xbd/small_damage_classification/output --test_csv /gws/nopw/j04/ai4er/users/jl2182/xbd/small_damage_classification/output_csv/train.csv --model_out /gws/nopw/j04/ai4er/users/jl2182/gtc-exposure/change_detection/xBD/xView2_baseline/model/classification_weights 
