#!/bin/bash

set -ex

# # # Download Data # # #

### Settlement Segmentation ###
# Random Forrest Classifier

wget -O settlement_segmentation/randomforest/killick_val.tiff "https://drive.google.com/uc?export=download&id=1sjnERn_H-4TvRJ_ffRkIoc79tKNkEAV2"
wget -O settlement_segmentation/randomforest/killick_classifier.pkl "https://drive.google.com/uc?export=download&id=1D3y9odtvpVRx-ZTCq2L8aHydPETAp2LD"


### Change Detection ###
# Ratio Method

# results

mkdir change_detection/ratio_method/download_data/
wget -O results.zip "https://drive.google.com/uc?export=download&id=18AngZi11uDFjNRYlM0kSdUPRB5Q0O8_v"
unzip results.zip
rm results.zip
mv results change_detection/ratio_method/download_data/

# records
wget -O records.zip "https://drive.google.com/uc?export=download&id=1PoXkx9sf5Aiw6HYIetTGFTrgy_JPOWb0"
unzip records.zip
rm records.zip
mv results change_detection/ratio_method/download_data/

# models
wget -O models.zip "https://drive.google.com/uc?export=download&id=18wdEMvBKjXdM8zB2kD9VRU2KO3v4ouBR"
unzip models.zip
rm models.zip
mv models change_detection/ratio_method/download_data/

# gradings
wget -O gradings.zip "https://drive.google.com/uc?export=download&id=14gH7lV6nGoaN4GQjzIwFVDT84J6QEMiT"
unzip gradings.zip
rm gradings.zip
mv gradings change_detection/ratio_method/download_data/

# geojsons
wget -O geojsons.zip "https://drive.google.com/uc?export=download&id=1ZDzQKo37f51ZC2uRVjT8YNSusaNODRol"
unzip download_data/geojsons.zip
rm geojsons.zip
mv geojsons change_detection/ratio_method/download_data/

# coastlines
wget -O coastlines.zip "https://drive.google.com/uc?export=download&id=1fx_WeWbRmSn9gWC8fuWAIUksaIQLay6u"
unzip coastlines.zip
rm coastlines.zip
mv coastlines change_detection/ratio_method/download_data/


### Exposure Quantification ###

wget -O exposure_quantification/GHS_png.zip "https://drive.google.com/uc?export=download&id=1WTohi_XZrJXyHzKVueKee-S3QJLtMocK"
unzip exposure_quantification/GHS_png.zip

rm exposure_quantification/GHS_png.zip


### Install dependencies ###

pip3 install -r binder/requirements.txt

jupyter lab clean

jupyter labextension install jupyter-leaflet @jupyter-widgets/jupyterlab-manager
jupyter nbextension enable --py --sys-prefix ipyleaflet

pip install numpy
pip install tensorflow
pip install descarteslabs
